version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=DB_NAME
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    ports:
      - "8888:5432"
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: "python LoyalitySystem/manage.py runserver 0.0.0.0:8000"
    image: loyality_code
    container_name: loyality_code
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - db


