# Generated by Django 4.1.6 on 2023-02-14 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_card', models.CharField(max_length=1)),
                ('number_card', models.IntegerField()),
                ('status_card', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('create_date_card', models.DateTimeField()),
                ('ending_date_card', models.DateTimeField()),
                ('last_activity_card', models.DateTimeField(auto_now=True)),
                ('amount_purchase', models.IntegerField(default=0)),
                ('discount_percent', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('sum_order', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_percent', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cards')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.orders')),
            ],
        ),
    ]
